import {ComfyUiCheckRequestDtoSchema, type ComfyUiCheckRequestDto} from "nbook/shared/dto/comfyui.dto";
import {loadGlobalEffectiveConfigSync} from "nbook/server/config/config-service";
import {checkComfyUi} from "nbook/server/comfyui/client";
import {validateBody} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "ComfyUI"
    ],
    "summary": "Check connectivity of the local ComfyUI server",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "baseURL": {
                            "type": "string",
                            "maxLength": 500
                        }
                    },
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "success": {
                                "type": "boolean"
                            },
                            "latencyMs": {
                                "nullable": true,
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9007199254740991
                            },
                            "message": {
                                "type": "string",
                                "minLength": 1
                            }
                        },
                        "required": [
                            "success",
                            "latencyMs",
                            "message"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

/**
 * ComfyUI 连接检查。body 可携带草稿 baseURL（设置页未保存时测试），缺省用已保存配置。
 * 任何失败都返回 {success:false, message}，不抛 5xx。
 */
export default defineEventHandler(async (event) => {
    const body = await validateBody<ComfyUiCheckRequestDto>(event, ComfyUiCheckRequestDtoSchema);
    const config = loadGlobalEffectiveConfigSync();
    const baseURL = body.baseURL?.trim() || config.comfyui.baseURL;
    return checkComfyUi(baseURL, config.comfyui.timeoutMs ?? 30_000);
});
