import {z} from "zod";
import {withProductWorkspaceFiles} from "nbook/server/runtime/product-startup";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withBoundProjectTargetMutation, parseWorkspaceFileHttpBinding} from "nbook/server/workspace-files/project-open-guard";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Delete a workspace file or directory",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "projectRoot": {
                            "description": "Project Workspace root, single directory name under Workspace Root",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "path": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Path to delete"
                        },
                        "recursive": {
                            "default": false,
                            "description": "Delete recursively",
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "path",
                        "recursive"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "success": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "success"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

const DeleteWorkspacePathBodySchema = z.object({
    projectRoot: z.string().optional(),
    publicId: z.string().optional(),
    workspaceKind: z.literal("user-assets").optional(),
    path: z.string().trim().min(1, "path 不能为空"),
    recursive: z.boolean().optional().default(false),
});

/**
 * 删除工作区文件或目录。
 */
export default defineEventHandler(async (event) => {
    const body = DeleteWorkspacePathBodySchema.parse(await readBody(event));
    const binding = parseWorkspaceFileHttpBinding(body);
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), binding);
    return withBoundProjectTargetMutation(target, binding, (handles) =>
        withProductWorkspaceFiles({target, handles}, async files => {
            await files.delete(body.path, body.recursive);
            return {success: true};
        }));
});
