import {z} from "zod";
import {withProductWorkspaceFiles} from "nbook/server/runtime/product-startup";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withBoundProjectTargetMutation, parseWorkspaceFileHttpBinding} from "nbook/server/workspace-files/project-open-guard";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Rename or move a workspace path",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "projectRoot": {
                            "description": "Project Workspace root, single directory name under Workspace Root",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "from": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Source path"
                        },
                        "to": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Destination path"
                        }
                    },
                    "required": [
                        "from",
                        "to"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK"
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

const RenameWorkspacePathBodySchema = z.object({
    projectRoot: z.string().optional(),
    publicId: z.string().optional(),
    workspaceKind: z.literal("user-assets").optional(),
    from: z.string().trim().min(1, "from 不能为空"),
    to: z.string().trim().min(1, "to 不能为空"),
});

/**
 * 移动或重命名工作区路径。
 */
export default defineEventHandler(async (event) => {
    const body = RenameWorkspacePathBodySchema.parse(await readBody(event));
    const binding = parseWorkspaceFileHttpBinding(body);
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), binding);
    return withBoundProjectTargetMutation(target, binding, (handles) =>
        withProductWorkspaceFiles({target, handles}, files => files.rename(body.from, body.to)));
});
