import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withBoundProjectTargetOperation, parseWorkspaceFileHttpBinding} from "nbook/server/workspace-files/project-open-guard";
import {withProductWorkspaceFiles} from "nbook/server/runtime/product-startup";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {createServerTiming} from "nbook/server/utils/server-timing";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Get file/directory metadata (stat)",
    "parameters": [
        {
            "name": "path",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Path to stat"
            },
            "description": "Path to stat"
        },
        {
            "name": "projectRoot",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Project Workspace root, single directory name under Workspace Root",
                "type": "string"
            },
            "description": "Project Workspace root, single directory name under Workspace Root"
        },
        {
            "name": "workspaceKind",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Use the global user assets workspace",
                "type": "string",
                "enum": [
                    "user-assets"
                ]
            },
            "description": "Use the global user assets workspace"
        }
    ],
    "responses": {
        "200": {
            "description": "OK"
        }
    }
} as never,
});






/**
 * 读取工作区文件或目录元信息。
 */
export default defineEventHandler(async (event) => {
    const timing = createServerTiming(event);
    const query = getQuery(event);
    const filePath = readRequiredQueryString(query.path, "path");
    const binding = parseWorkspaceFileHttpBinding(query);
    const target = await timing.measure("files.stat.resolve", () => resolveWorkspaceFileTarget(runtimePathsFromEnv(), binding));
    return withBoundProjectTargetOperation(target, binding, (handles) => (
        timing.measure("files.stat.read", () => withProductWorkspaceFiles({target, handles}, files => files.stat(filePath)))
    ));
});

/**
 * 读取必填查询字符串。
 */
function readRequiredQueryString(value: unknown, key: string): string {
    if (typeof value !== "string" || !value.trim()) {
        throw createError({statusCode: 400, message: `${key} 不能为空`});
    }
    return value.trim();
}
