import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withBoundProjectTargetOperation, parseWorkspaceFileHttpBinding} from "nbook/server/workspace-files/project-open-guard";
import {withProductWorkspaceFiles} from "nbook/server/runtime/product-startup";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {createServerTiming} from "nbook/server/utils/server-timing";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Read workspace tree snapshot",
    "parameters": [
        {
            "name": "projectRoot",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Project Workspace root, single directory name under Workspace Root",
                "type": "string"
            },
            "description": "Project Workspace root, single directory name under Workspace Root"
        },
        {
            "name": "workspaceKind",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Use the global user assets workspace",
                "type": "string",
                "enum": [
                    "user-assets"
                ]
            },
            "description": "Use the global user assets workspace"
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "nodes": {
                                "type": "array",
                                "items": {},
                                "description": "Workspace file nodes"
                            },
                            "issues": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "level": {
                                            "type": "string",
                                            "enum": [
                                                "P1",
                                                "P2",
                                                "P3",
                                                "WARN"
                                            ]
                                        },
                                        "code": {
                                            "type": "string"
                                        },
                                        "path": {
                                            "type": "string"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "line": {
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "level",
                                        "code",
                                        "path",
                                        "message"
                                    ],
                                    "additionalProperties": false
                                },
                                "description": "Project Workspace issues; empty for user-assets"
                            },
                            "revision": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9007199254740991,
                                "description": "Project Workspace File Index revision"
                            },
                            "validatedAt": {
                                "type": "string",
                                "description": "ISO timestamp for the latest snapshot validation"
                            }
                        },
                        "required": [
                            "nodes",
                            "issues",
                            "revision",
                            "validatedAt"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});






/**
 * 读取工作区文件树。
 */
export default defineEventHandler(async (event) => {
    const timing = createServerTiming(event);
    const query = getQuery(event);
    const binding = parseWorkspaceFileHttpBinding(query);
    const type = typeof query.type === "string" && query.type.trim() ? query.type.trim() : null;
    const depth = typeof query.depth === "string" ? Number.parseInt(query.depth, 10) : null;
    const targets = parseTargets(query.target);
    const parsedDepth = Number.isSafeInteger(depth) ? depth : null;

    const target = await timing.measure("files.tree.resolve", () => (
        resolveWorkspaceFileTarget(runtimePathsFromEnv(), binding)
    ));
    return withBoundProjectTargetOperation(target, binding, (handles) => (
        timing.measure(target.kind === "project-workspace" ? "files.tree.index" : "files.tree.scan", () => (
            withProductWorkspaceFiles({target, handles}, files => files.tree({targets, type, depth: parsedDepth}))
        ))
    ));
});

/**
 * 解析 target 查询参数。
 */
function parseTargets(value: unknown): string[] {
    if (Array.isArray(value)) {
        return value.filter((item): item is string => typeof item === "string" && item.trim().length > 0);
    }
    if (typeof value === "string" && value.trim()) {
        return [value.trim()];
    }
    return [];
}
