import {z} from "zod";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withBoundProjectTargetMutation, parseWorkspaceFileHttpBinding} from "nbook/server/workspace-files/project-open-guard";
import {withProductWorkspaceFiles} from "nbook/server/runtime/product-startup";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Write content to a workspace file",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "projectRoot": {
                            "description": "Project Workspace root, single directory name under Workspace Root",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "path": {
                            "type": "string",
                            "minLength": 1,
                            "description": "File path"
                        },
                        "content": {
                            "type": "string",
                            "description": "File content"
                        }
                    },
                    "required": [
                        "path",
                        "content"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK"
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

const WriteWorkspaceFileBodySchema = z.object({
    projectRoot: z.string().optional(),
    publicId: z.string().optional(),
    workspaceKind: z.literal("user-assets").optional(),
    path: z.string().trim().min(1, "path 不能为空"),
    content: z.string(),
    baseContent: z.string().optional(),
    expectedMtimeMs: z.number().nullable().optional(),
    force: z.boolean().optional().default(false),
});

/**
 * 覆盖写入工作区文本文件。
 */
export default defineEventHandler(async (event) => {
    const body = WriteWorkspaceFileBodySchema.parse(await readBody(event));
    const binding = parseWorkspaceFileHttpBinding(body);
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), binding);
    return withBoundProjectTargetMutation(target, binding, (handles) => (
        withProductWorkspaceFiles({target, handles}, files => files.write(body))
    ));
});
