import {requireProjectPathQuery} from "nbook/server/utils/novel-chapter";
import {assertProjectWorkspaceDirectory} from "nbook/server/workspace-files/project-workspace";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {assertProjectOpen, markProjectActivity, ProjectNotOpenError} from "nbook/server/workspace-files/project-session";
import {createProjectNotOpenHttpError} from "nbook/server/workspace-files/project-open-guard";
import {cancelJob, ComfyUiJobNotFoundError} from "nbook/server/comfyui/job-manager";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "ComfyUI"
    ],
    "summary": "Cancel an illustration generation job",
    "parameters": [
        {
            "name": "jobId",
            "in": "path",
            "required": true,
            "schema": {
                "type": "string"
            }
        },
        {
            "name": "projectPath",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace path, for example workspace/<project>"
            },
            "description": "Project Workspace path, for example workspace/<project>"
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "jobId": {
                                "type": "string",
                                "minLength": 1
                            },
                            "projectPath": {
                                "type": "string",
                                "minLength": 1
                            },
                            "status": {
                                "type": "string",
                                "enum": [
                                    "pending",
                                    "running",
                                    "downloading",
                                    "completed",
                                    "failed",
                                    "cancelled"
                                ]
                            },
                            "progress": {
                                "nullable": true,
                                "type": "number",
                                "minimum": 0,
                                "maximum": 1
                            },
                            "progressNode": {
                                "nullable": true,
                                "type": "string"
                            },
                            "promptId": {
                                "nullable": true,
                                "type": "string"
                            },
                            "params": {
                                "type": "object",
                                "properties": {
                                    "positive": {
                                        "type": "string",
                                        "minLength": 1,
                                        "maxLength": 4000
                                    },
                                    "negative": {
                                        "default": "",
                                        "type": "string",
                                        "maxLength": 4000
                                    },
                                    "width": {
                                        "type": "integer",
                                        "minimum": 64,
                                        "maximum": 4096
                                    },
                                    "height": {
                                        "type": "integer",
                                        "minimum": 64,
                                        "maximum": 4096
                                    },
                                    "steps": {
                                        "type": "integer",
                                        "minimum": 1,
                                        "maximum": 150
                                    },
                                    "cfg": {
                                        "type": "number",
                                        "minimum": 0,
                                        "maximum": 30
                                    },
                                    "seed": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "workflowId": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "string",
                                        "minLength": 1
                                    }
                                },
                                "required": [
                                    "positive",
                                    "negative",
                                    "width",
                                    "height",
                                    "steps",
                                    "cfg",
                                    "seed",
                                    "workflowId"
                                ],
                                "additionalProperties": false
                            },
                            "resolvedSeed": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9007199254740991
                            },
                            "images": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "path": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "path"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "error": {
                                "nullable": true,
                                "type": "string"
                            },
                            "createdAt": {
                                "type": "number"
                            },
                            "updatedAt": {
                                "type": "number"
                            }
                        },
                        "required": [
                            "jobId",
                            "projectPath",
                            "status",
                            "progress",
                            "progressNode",
                            "promptId",
                            "params",
                            "resolvedSeed",
                            "images",
                            "error",
                            "createdAt",
                            "updatedAt"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});

/**
 * 取消生图任务：pending 直接标记，running 先尽力 POST /interrupt。幂等。
 */
export default defineEventHandler(async (event) => {
    try {
        const workspaceRoot = runtimePathsFromEnv().workspaceRoot;
        const projectPath = await assertProjectWorkspaceDirectory(workspaceRoot, requireProjectPathQuery(event));
        assertProjectOpen(projectPath);
        markProjectActivity(projectPath);
        return await cancelJob(getRouterParam(event, "jobId") ?? "");
    } catch (error) {
        if (error instanceof ProjectNotOpenError) {
            throw createProjectNotOpenHttpError(error);
        }
        if (error instanceof ComfyUiJobNotFoundError) {
            throw createError({statusCode: 404, message: error.message});
        }
        throw error;
    }
});
