import {ComfyUiUpdateWorkflowRequestDtoSchema, type ComfyUiUpdateWorkflowRequestDto} from "nbook/shared/dto/comfyui.dto";
import {ComfyUiWorkflowNotFoundError, updateWorkflow} from "nbook/server/comfyui/user-workflows";
import {validateBody} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "ComfyUI"
    ],
    "summary": "Update an imported workflow's name or injection mapping",
    "parameters": [
        {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
                "type": "string"
            }
        }
    ],
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "mapping": {
                            "type": "object",
                            "properties": {
                                "positive": {
                                    "nullable": true,
                                    "type": "object",
                                    "properties": {
                                        "nodeId": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "field": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "nodeId",
                                        "field"
                                    ],
                                    "additionalProperties": false
                                },
                                "negative": {
                                    "nullable": true,
                                    "type": "object",
                                    "properties": {
                                        "nodeId": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "field": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "nodeId",
                                        "field"
                                    ],
                                    "additionalProperties": false
                                },
                                "width": {
                                    "nullable": true,
                                    "type": "object",
                                    "properties": {
                                        "nodeId": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "field": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "nodeId",
                                        "field"
                                    ],
                                    "additionalProperties": false
                                },
                                "height": {
                                    "nullable": true,
                                    "type": "object",
                                    "properties": {
                                        "nodeId": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "field": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "nodeId",
                                        "field"
                                    ],
                                    "additionalProperties": false
                                },
                                "seed": {
                                    "nullable": true,
                                    "type": "object",
                                    "properties": {
                                        "nodeId": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "field": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "nodeId",
                                        "field"
                                    ],
                                    "additionalProperties": false
                                },
                                "steps": {
                                    "nullable": true,
                                    "type": "object",
                                    "properties": {
                                        "nodeId": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "field": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "nodeId",
                                        "field"
                                    ],
                                    "additionalProperties": false
                                },
                                "cfg": {
                                    "nullable": true,
                                    "type": "object",
                                    "properties": {
                                        "nodeId": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "field": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "nodeId",
                                        "field"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "required": [
                                "positive",
                                "negative",
                                "width",
                                "height",
                                "seed",
                                "steps",
                                "cfg"
                            ],
                            "additionalProperties": false
                        }
                    },
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string",
                                "minLength": 1
                            },
                            "name": {
                                "type": "string",
                                "minLength": 1
                            },
                            "builtin": {
                                "type": "boolean"
                            },
                            "mapping": {
                                "type": "object",
                                "properties": {
                                    "positive": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "negative": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "width": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "height": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "seed": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "steps": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "cfg": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    }
                                },
                                "required": [
                                    "positive",
                                    "negative",
                                    "width",
                                    "height",
                                    "seed",
                                    "steps",
                                    "cfg"
                                ],
                                "additionalProperties": false
                            },
                            "issues": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "updatedAt": {
                                "nullable": true,
                                "type": "number"
                            }
                        },
                        "required": [
                            "id",
                            "name",
                            "builtin",
                            "mapping",
                            "issues",
                            "updatedAt"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

/**
 * 更新自定义工作流的名称或注入点 mapping。
 */
export default defineEventHandler(async (event) => {
    const id = getRouterParam(event, "id") ?? "";
    const body = await validateBody<ComfyUiUpdateWorkflowRequestDto>(event, ComfyUiUpdateWorkflowRequestDtoSchema);
    try {
        return await updateWorkflow(id, body);
    } catch (error) {
        if (error instanceof ComfyUiWorkflowNotFoundError) {
            throw createError({statusCode: 404, message: error.message});
        }
        throw error;
    }
});
