import {deleteWorkflow} from "nbook/server/comfyui/user-workflows";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "ComfyUI"
    ],
    "summary": "Delete an imported workflow",
    "parameters": [
        {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
                "type": "string"
            }
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "ok": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "ok"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});

/**
 * 删除自定义工作流（幂等：不存在也返回成功）。
 */
export default defineEventHandler(async (event) => {
    const id = getRouterParam(event, "id") ?? "";
    await deleteWorkflow(id);
    return {ok: true};
});
