import {ComfyUiImportWorkflowRequestDtoSchema, type ComfyUiImportWorkflowRequestDto} from "nbook/shared/dto/comfyui.dto";
import {importWorkflow} from "nbook/server/comfyui/user-workflows";
import {validateBody} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "ComfyUI"
    ],
    "summary": "Import a ComfyUI API-format workflow",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "workflow": {
                            "type": "object",
                            "additionalProperties": {}
                        }
                    },
                    "required": [
                        "name",
                        "workflow"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string",
                                "minLength": 1
                            },
                            "name": {
                                "type": "string",
                                "minLength": 1
                            },
                            "builtin": {
                                "type": "boolean"
                            },
                            "mapping": {
                                "type": "object",
                                "properties": {
                                    "positive": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "negative": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "width": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "height": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "seed": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "steps": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "cfg": {
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "nodeId": {
                                                "type": "string",
                                                "minLength": 1
                                            },
                                            "field": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "required": [
                                            "nodeId",
                                            "field"
                                        ],
                                        "additionalProperties": false
                                    }
                                },
                                "required": [
                                    "positive",
                                    "negative",
                                    "width",
                                    "height",
                                    "seed",
                                    "steps",
                                    "cfg"
                                ],
                                "additionalProperties": false
                            },
                            "issues": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "updatedAt": {
                                "nullable": true,
                                "type": "number"
                            }
                        },
                        "required": [
                            "id",
                            "name",
                            "builtin",
                            "mapping",
                            "issues",
                            "updatedAt"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

/**
 * 导入 ComfyUI「导出 API」JSON 为自定义工作流，返回自动识别的注入点 mapping 与 issues。
 * 工作流 JSON 最大 2MB。
 */
export default defineEventHandler(async (event) => {
    const body = await validateBody<ComfyUiImportWorkflowRequestDto>(event, ComfyUiImportWorkflowRequestDtoSchema, {maxBytes: 2 * 1024 * 1024});
    return importWorkflow(body);
});
