import {listWorkflows} from "nbook/server/comfyui/user-workflows";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "ComfyUI"
    ],
    "summary": "List ComfyUI workflows (built-in + imported)",
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "name": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "builtin": {
                                            "type": "boolean"
                                        },
                                        "mapping": {
                                            "type": "object",
                                            "properties": {
                                                "positive": {
                                                    "nullable": true,
                                                    "type": "object",
                                                    "properties": {
                                                        "nodeId": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        },
                                                        "field": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        }
                                                    },
                                                    "required": [
                                                        "nodeId",
                                                        "field"
                                                    ],
                                                    "additionalProperties": false
                                                },
                                                "negative": {
                                                    "nullable": true,
                                                    "type": "object",
                                                    "properties": {
                                                        "nodeId": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        },
                                                        "field": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        }
                                                    },
                                                    "required": [
                                                        "nodeId",
                                                        "field"
                                                    ],
                                                    "additionalProperties": false
                                                },
                                                "width": {
                                                    "nullable": true,
                                                    "type": "object",
                                                    "properties": {
                                                        "nodeId": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        },
                                                        "field": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        }
                                                    },
                                                    "required": [
                                                        "nodeId",
                                                        "field"
                                                    ],
                                                    "additionalProperties": false
                                                },
                                                "height": {
                                                    "nullable": true,
                                                    "type": "object",
                                                    "properties": {
                                                        "nodeId": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        },
                                                        "field": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        }
                                                    },
                                                    "required": [
                                                        "nodeId",
                                                        "field"
                                                    ],
                                                    "additionalProperties": false
                                                },
                                                "seed": {
                                                    "nullable": true,
                                                    "type": "object",
                                                    "properties": {
                                                        "nodeId": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        },
                                                        "field": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        }
                                                    },
                                                    "required": [
                                                        "nodeId",
                                                        "field"
                                                    ],
                                                    "additionalProperties": false
                                                },
                                                "steps": {
                                                    "nullable": true,
                                                    "type": "object",
                                                    "properties": {
                                                        "nodeId": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        },
                                                        "field": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        }
                                                    },
                                                    "required": [
                                                        "nodeId",
                                                        "field"
                                                    ],
                                                    "additionalProperties": false
                                                },
                                                "cfg": {
                                                    "nullable": true,
                                                    "type": "object",
                                                    "properties": {
                                                        "nodeId": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        },
                                                        "field": {
                                                            "type": "string",
                                                            "minLength": 1
                                                        }
                                                    },
                                                    "required": [
                                                        "nodeId",
                                                        "field"
                                                    ],
                                                    "additionalProperties": false
                                                }
                                            },
                                            "required": [
                                                "positive",
                                                "negative",
                                                "width",
                                                "height",
                                                "seed",
                                                "steps",
                                                "cfg"
                                            ],
                                            "additionalProperties": false
                                        },
                                        "issues": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        },
                                        "updatedAt": {
                                            "nullable": true,
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "name",
                                        "builtin",
                                        "mapping",
                                        "issues",
                                        "updatedAt"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        },
                        "required": [
                            "items"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});

/**
 * 列出全部 ComfyUI 工作流（内置模板 + 用户导入），供设置页与生图面板下拉使用。
 */
export default defineEventHandler(async () => {
    return {items: await listWorkflows()};
});
