import {requireProjectPathQuery, validateBody} from "nbook/server/utils/novel-chapter";
import {assertProjectWorkspaceDirectory} from "nbook/server/workspace-files/project-workspace";
import {resolveProjectWorkspaceRoot} from "nbook/server/workspace-files/project-path";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {assertProjectOpen, markProjectActivity, ProjectNotOpenError} from "nbook/server/workspace-files/project-session";
import {createProjectNotOpenHttpError} from "nbook/server/workspace-files/project-open-guard";
import {RpInsertIllustrationRequestDtoSchema, type RpInsertIllustrationRequestDto} from "nbook/shared/dto/comfyui.dto";
import {insertIllustrationAfterAnchor, RpAnchorNotFoundError, RpTickNotFoundError} from "nbook/server/rp/prose-store";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "ComfyUI"
    ],
    "summary": "Insert an illustration into RP tick prose after an anchor",
    "parameters": [
        {
            "name": "projectPath",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace path, for example workspace/<project>"
            },
            "description": "Project Workspace path, for example workspace/<project>"
        }
    ],
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "tickDir": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 200
                        },
                        "anchorText": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 500
                        },
                        "occurrence": {
                            "default": 0,
                            "type": "integer",
                            "minimum": 0,
                            "maximum": 9007199254740991
                        },
                        "imagePath": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 500
                        },
                        "alt": {
                            "default": "",
                            "type": "string",
                            "maxLength": 200
                        },
                        "fallback": {
                            "default": "none",
                            "type": "string",
                            "enum": [
                                "none",
                                "append"
                            ]
                        }
                    },
                    "required": [
                        "tickDir",
                        "anchorText",
                        "occurrence",
                        "imagePath",
                        "alt",
                        "fallback"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "mode": {
                                "type": "string",
                                "enum": [
                                    "anchored",
                                    "appended"
                                ]
                            }
                        },
                        "required": [
                            "mode"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

/**
 * RP 正文插图写回：在指定 tick 的 prose.md 中、锚点文字所在段落之后插入图片行。
 * 锚点找不到且 fallback=none 时返回 409 + data.code=ANCHOR_NOT_FOUND，前端确认后带 fallback=append 重试。
 */
export default defineEventHandler(async (event) => {
    try {
        const workspaceRoot = runtimePathsFromEnv().workspaceRoot;
        const projectPath = await assertProjectWorkspaceDirectory(workspaceRoot, requireProjectPathQuery(event));
        assertProjectOpen(projectPath);
        markProjectActivity(projectPath);
        const projectRoot = resolveProjectWorkspaceRoot(workspaceRoot, projectPath);
        const body = await validateBody<RpInsertIllustrationRequestDto>(event, RpInsertIllustrationRequestDtoSchema);
        return await insertIllustrationAfterAnchor(projectRoot, body);
    } catch (error) {
        if (error instanceof ProjectNotOpenError) {
            throw createProjectNotOpenHttpError(error);
        }
        if (error instanceof RpTickNotFoundError) {
            throw createError({statusCode: 404, message: error.message});
        }
        if (error instanceof RpAnchorNotFoundError) {
            throw createError({statusCode: 409, message: error.message, data: {code: "ANCHOR_NOT_FOUND"}});
        }
        throw error;
    }
});
