import {requireProjectPathQuery, validateBody} from "nbook/server/utils/novel-chapter";
import {assertProjectWorkspaceDirectory} from "nbook/server/workspace-files/project-workspace";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {assertProjectOpen, markProjectActivity, ProjectNotOpenError} from "nbook/server/workspace-files/project-session";
import {createProjectNotOpenHttpError} from "nbook/server/workspace-files/project-open-guard";
import {ComfyUiDistillRequestDtoSchema, type ComfyUiDistillRequestDto} from "nbook/shared/dto/comfyui.dto";
import {ComfyUiDistillError, distillIllustrationPrompt} from "nbook/server/comfyui/prompt-distill";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "ComfyUI"
    ],
    "summary": "Distill selected prose into an English image prompt",
    "parameters": [
        {
            "name": "projectPath",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace path, for example workspace/<project>"
            },
            "description": "Project Workspace path, for example workspace/<project>"
        }
    ],
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "text": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 8000
                        },
                        "styleHint": {
                            "type": "string",
                            "maxLength": 500
                        }
                    },
                    "required": [
                        "text"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "positive": {
                                "type": "string",
                                "minLength": 1
                            },
                            "negative": {
                                "type": "string"
                            },
                            "modelKey": {
                                "type": "string",
                                "minLength": 1
                            }
                        },
                        "required": [
                            "positive",
                            "negative",
                            "modelKey"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

/**
 * 提示词蒸馏：把选中的正文文字转成 Anima 风格英文生图提示词（LLM 单次调用）。
 */
export default defineEventHandler(async (event) => {
    try {
        const workspaceRoot = runtimePathsFromEnv().workspaceRoot;
        const projectPath = await assertProjectWorkspaceDirectory(workspaceRoot, requireProjectPathQuery(event));
        assertProjectOpen(projectPath);
        markProjectActivity(projectPath);
        const body = await validateBody<ComfyUiDistillRequestDto>(event, ComfyUiDistillRequestDtoSchema);
        return await distillIllustrationPrompt({projectPath, text: body.text, styleHint: body.styleHint});
    } catch (error) {
        if (error instanceof ProjectNotOpenError) {
            throw createProjectNotOpenHttpError(error);
        }
        if (error instanceof ComfyUiDistillError) {
            throw createError({statusCode: error.statusCode, message: error.message});
        }
        throw error;
    }
});
