import {requireProjectPathQuery, validateBody} from "nbook/server/utils/novel-chapter";
import {assertProjectWorkspaceDirectory} from "nbook/server/workspace-files/project-workspace";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {assertProjectOpen, markProjectActivity, ProjectNotOpenError} from "nbook/server/workspace-files/project-session";
import {createProjectNotOpenHttpError} from "nbook/server/workspace-files/project-open-guard";
import {ComfyUiCreateJobRequestDtoSchema, type ComfyUiCreateJobRequestDto} from "nbook/shared/dto/comfyui.dto";
import {ComfyUiJobInputError, createIllustrationJob} from "nbook/server/comfyui/job-manager";
import {ComfyUiRequestError} from "nbook/server/comfyui/client";
import {ComfyUiWorkflowNotFoundError} from "nbook/server/comfyui/user-workflows";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "ComfyUI"
    ],
    "summary": "Create an illustration generation job",
    "parameters": [
        {
            "name": "projectPath",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace path, for example workspace/<project>"
            },
            "description": "Project Workspace path, for example workspace/<project>"
        }
    ],
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "positive": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 4000
                        },
                        "negative": {
                            "default": "",
                            "type": "string",
                            "maxLength": 4000
                        },
                        "width": {
                            "type": "integer",
                            "minimum": 64,
                            "maximum": 4096
                        },
                        "height": {
                            "type": "integer",
                            "minimum": 64,
                            "maximum": 4096
                        },
                        "steps": {
                            "type": "integer",
                            "minimum": 1,
                            "maximum": 150
                        },
                        "cfg": {
                            "type": "number",
                            "minimum": 0,
                            "maximum": 30
                        },
                        "seed": {
                            "default": null,
                            "nullable": true,
                            "type": "integer",
                            "minimum": 0,
                            "maximum": 9007199254740991
                        },
                        "workflowId": {
                            "default": null,
                            "nullable": true,
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "required": [
                        "positive",
                        "negative",
                        "width",
                        "height",
                        "steps",
                        "cfg",
                        "seed",
                        "workflowId"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "jobId": {
                                "type": "string",
                                "minLength": 1
                            },
                            "projectPath": {
                                "type": "string",
                                "minLength": 1
                            },
                            "status": {
                                "type": "string",
                                "enum": [
                                    "pending",
                                    "running",
                                    "downloading",
                                    "completed",
                                    "failed",
                                    "cancelled"
                                ]
                            },
                            "progress": {
                                "nullable": true,
                                "type": "number",
                                "minimum": 0,
                                "maximum": 1
                            },
                            "progressNode": {
                                "nullable": true,
                                "type": "string"
                            },
                            "promptId": {
                                "nullable": true,
                                "type": "string"
                            },
                            "params": {
                                "type": "object",
                                "properties": {
                                    "positive": {
                                        "type": "string",
                                        "minLength": 1,
                                        "maxLength": 4000
                                    },
                                    "negative": {
                                        "default": "",
                                        "type": "string",
                                        "maxLength": 4000
                                    },
                                    "width": {
                                        "type": "integer",
                                        "minimum": 64,
                                        "maximum": 4096
                                    },
                                    "height": {
                                        "type": "integer",
                                        "minimum": 64,
                                        "maximum": 4096
                                    },
                                    "steps": {
                                        "type": "integer",
                                        "minimum": 1,
                                        "maximum": 150
                                    },
                                    "cfg": {
                                        "type": "number",
                                        "minimum": 0,
                                        "maximum": 30
                                    },
                                    "seed": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "workflowId": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "string",
                                        "minLength": 1
                                    }
                                },
                                "required": [
                                    "positive",
                                    "negative",
                                    "width",
                                    "height",
                                    "steps",
                                    "cfg",
                                    "seed",
                                    "workflowId"
                                ],
                                "additionalProperties": false
                            },
                            "resolvedSeed": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9007199254740991
                            },
                            "images": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "path": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "path"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "error": {
                                "nullable": true,
                                "type": "string"
                            },
                            "createdAt": {
                                "type": "number"
                            },
                            "updatedAt": {
                                "type": "number"
                            }
                        },
                        "required": [
                            "jobId",
                            "projectPath",
                            "status",
                            "progress",
                            "progressNode",
                            "promptId",
                            "params",
                            "resolvedSeed",
                            "images",
                            "error",
                            "createdAt",
                            "updatedAt"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

/**
 * 创建生图任务：构建工作流并提交本地 ComfyUI，立即返回 pending/running job。
 * 生成的图片最终落盘到该项目的 assets/illustrations/，进度经 GET /api/comfyui/jobs/events 推送。
 */
export default defineEventHandler(async (event) => {
    try {
        const workspaceRoot = runtimePathsFromEnv().workspaceRoot;
        const projectPath = await assertProjectWorkspaceDirectory(workspaceRoot, requireProjectPathQuery(event));
        assertProjectOpen(projectPath);
        markProjectActivity(projectPath);
        const body = await validateBody<ComfyUiCreateJobRequestDto>(event, ComfyUiCreateJobRequestDtoSchema);
        return await createIllustrationJob({projectPath, request: body});
    } catch (error) {
        if (error instanceof ProjectNotOpenError) {
            throw createProjectNotOpenHttpError(error);
        }
        if (error instanceof ComfyUiJobInputError || error instanceof ComfyUiWorkflowNotFoundError) {
            throw createError({statusCode: 400, message: error.message});
        }
        if (error instanceof ComfyUiRequestError) {
            throw createError({statusCode: error.statusCode, message: error.message});
        }
        throw error;
    }
});
