import {z} from "zod";
import {createWorkspaceFileTracked, USER_LOCAL_ACTOR} from "nbook/server/workspace-history/tracked-workspace-files";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {invalidateProjectWorkspaceIndexAfterMutation} from "nbook/server/workspace-files/project-workspace-index";
import {assertProjectOpenForTarget} from "nbook/server/workspace-files/project-open-guard";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Create a new workspace file",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "root": {
                            "description": "Workspace root directory",
                            "type": "string"
                        },
                        "novelId": {
                            "description": "Novel id used to resolve isolated workspace",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "path": {
                            "type": "string",
                            "minLength": 1,
                            "description": "File path"
                        },
                        "content": {
                            "description": "Initial file content",
                            "type": "string"
                        }
                    },
                    "required": [
                        "path"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK"
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});





const CreateWorkspaceFileBodySchema = z.object({
    projectPath: z.string().optional(),
    workspaceKind: z.literal("user-assets").optional(),
    path: z.string().trim().min(1, "path 不能为空"),
    content: z.string().optional(),
});

/**
 * 创建工作区文本文件。
 */
export default defineEventHandler(async (event) => {
    const body = CreateWorkspaceFileBodySchema.parse(await readBody(event));
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), body);
    assertProjectOpenForTarget(target);
    const node = await createWorkspaceFileTracked({
        target,
        filePath: body.path,
        content: body.content,
        actor: USER_LOCAL_ACTOR,
    });
    invalidateProjectWorkspaceIndexAfterMutation(target);
    return node;
});
