import {readWorkspaceBinaryFile} from "nbook/server/workspace-files/workspace-files";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {assertProjectOpenForTarget} from "nbook/server/workspace-files/project-open-guard";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {imageMimeType} from "nbook/server/agent/attachments/agent-attachment-codec";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Serve a workspace image file as raw bytes",
    "parameters": [
        {
            "name": "projectPath",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Project Workspace path, for example workspace/<project>",
                "type": "string"
            },
            "description": "Project Workspace path, for example workspace/<project>"
        },
        {
            "name": "workspaceKind",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Use the global user assets workspace",
                "type": "string",
                "enum": [
                    "user-assets"
                ]
            },
            "description": "Use the global user assets workspace"
        },
        {
            "name": "path",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Image file path relative to the workspace root"
            },
            "description": "Image file path relative to the workspace root"
        }
    ],
    "responses": {
        "200": {
            "description": "OK"
        }
    }
} as never,
});

/**
 * 工作区图片 raw serve：把 project workspace 内的图片文件以原始字节返回，
 * 供正文 markdown 中的相对路径插图（如 assets/illustrations/xxx.png）在前端渲染。
 *
 * 安全边界：
 * - 路径复用 workspace-files 的归一 + realpath 越界防护；
 * - Content-Type 只按魔数判定（PNG/JPEG/GIF/WebP），非图片一律 404，不嗅探不透传扩展名；
 * - ETag 用 mtime-size，命中 if-none-match 返回 304；图片可被覆盖，不使用 immutable。
 */
export default defineEventHandler(async (event) => {
    const query = getQuery(event);
    const filePath = typeof query.path === "string" && query.path.trim() ? query.path.trim() : null;
    if (!filePath) {
        throw createError({statusCode: 400, message: "path 不能为空"});
    }
    const projectPath = typeof query.projectPath === "string" ? query.projectPath : undefined;
    const workspaceKind = query.workspaceKind === "user-assets" ? query.workspaceKind : undefined;
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), {projectPath, workspaceKind});
    assertProjectOpenForTarget(target);

    let file: {bytes: Buffer; mtimeMs: number; size: number};
    try {
        file = await readWorkspaceBinaryFile(target.root, filePath);
    } catch (error) {
        if (typeof error === "object" && error !== null && "code" in error && (error as {code?: string}).code === "ENOENT") {
            throw createError({statusCode: 404, message: `文件不存在：${filePath}`});
        }
        if (error instanceof Error && error.message.startsWith("Path is outside")) {
            throw createError({statusCode: 400, message: "路径越界"});
        }
        throw error;
    }

    const mime = imageMimeType(file.bytes);
    if (!mime) {
        throw createError({statusCode: 404, message: "不是可识别的图片文件"});
    }

    const etag = `"${String(Math.trunc(file.mtimeMs))}-${String(file.size)}"`;
    setResponseHeader(event, "ETag", etag);
    setResponseHeader(event, "Cache-Control", "private, max-age=3600, must-revalidate");
    setResponseHeader(event, "X-Content-Type-Options", "nosniff");
    if (getRequestHeader(event, "if-none-match") === etag) {
        setResponseStatus(event, 304);
        return null;
    }
    setResponseHeader(event, "Content-Type", mime);
    setResponseHeader(event, "Content-Disposition", "inline");
    return file.bytes;
});
