import {statWorkspacePath} from "nbook/server/workspace-files/workspace-files";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {assertProjectOpenForTarget} from "nbook/server/workspace-files/project-open-guard";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Get file/directory metadata (stat)",
    "parameters": [
        {
            "name": "path",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Path to stat"
            },
            "description": "Path to stat"
        },
        {
            "name": "root",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Workspace root directory",
                "type": "string"
            },
            "description": "Workspace root directory"
        },
        {
            "name": "novelId",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Novel id used to resolve isolated workspace",
                "type": "string"
            },
            "description": "Novel id used to resolve isolated workspace"
        },
        {
            "name": "workspaceKind",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Use the global user assets workspace",
                "type": "string",
                "enum": [
                    "user-assets"
                ]
            },
            "description": "Use the global user assets workspace"
        }
    ],
    "responses": {
        "200": {
            "description": "OK"
        }
    }
} as never,
});






/**
 * 读取工作区文件或目录元信息。
 */
export default defineEventHandler(async (event) => {
    const query = getQuery(event);
    const filePath = readRequiredQueryString(query.path, "path");
    const projectPath = typeof query.projectPath === "string" ? query.projectPath : undefined;
    const workspaceKind = query.workspaceKind === "user-assets" ? query.workspaceKind : undefined;
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), {projectPath, workspaceKind});
    assertProjectOpenForTarget(target);
    return statWorkspacePath(target.root, filePath);
});

/**
 * 读取必填查询字符串。
 */
function readRequiredQueryString(value: unknown, key: string): string {
    if (typeof value !== "string" || !value.trim()) {
        throw createError({statusCode: 400, message: `${key} 不能为空`});
    }
    return value.trim();
}
