import {mkdir, unlink, writeFile} from "node:fs/promises";
import {homedir} from "node:os";
import {dirname, isAbsolute, resolve} from "node:path";
import type {AgentTool, AgentToolResult} from "@oh-my-pi/pi-agent-core";
import {
    EditSession,
    EditStore,
    editDescription,
    editGrammar,
    type EditPolicy,
    type EditVaultRoot,
    type EditWriteRequest,
    type EditWriteResponse,
} from "@oh-my-pi/pi-natives";

export type EditToolMode = "replace" | "patch" | "apply_patch" | "hashline";

export interface EditToolOptions {
    readonly cwd: string;
    /** 编辑模式；默认 `hashline`（先读后改的行锚协议）。 */
    readonly mode?: EditToolMode;
    /** 快照/寄存器存储；同一 harness 复用同一个实例，跨调用保持 tag 与 clipboard。 */
    readonly store?: EditStore;
    /** 写前确认；返回 false 时本次编辑整体拒绝、磁盘不变。默认全部允许。 */
    readonly confirmWrite?: (request: EditWriteRequest) => Promise<boolean> | boolean;
    readonly localSandboxRoot?: string;
    readonly vaultRoots?: readonly EditVaultRoot[];
    readonly homeDir?: string;
    /** 允许模糊匹配（OMP 语义）；默认 true。 */
    readonly allowFuzzy?: boolean;
    /** 强制「只改已展示的行」；默认 true（OMP 语义）。 */
    readonly enforceSeenLines?: boolean;
    readonly fuzzyThreshold?: number;
}

/** 宿主拒绝写入时抛出，只在本模块内捕获，不会冒泡到工具调用方。 */
class WriteDeniedError extends Error {
    constructor(readonly request: EditWriteRequest) {
        super(`已拒绝写入：${request.displayPath}`);
        this.name = "WriteDeniedError";
    }
}

function errorResult(text: string): AgentToolResult {
    return {content: [{type: "text", text}], isError: true};
}

/**
 * 基于 OMP `EditSession` 的编辑工具：模式装配、写回落盘、写前确认都在这里；
 * 语义（陈旧 tag 重映射、未展示行守卫、模糊匹配）完全交给 OMP 引擎。
 */
export function createEditTool(options: EditToolOptions): AgentTool {
    const mode: EditToolMode = options.mode ?? "hashline";
    const store = options.store ?? new EditStore();
    const homeDir = options.homeDir ?? homedir();
    const grammar = editGrammar(mode);

    const policy: EditPolicy = {
        cwd: options.cwd,
        mode,
        allowFuzzy: options.allowFuzzy ?? true,
        fuzzyThreshold: options.fuzzyThreshold ?? 0.8,
        enforceSeenLines: options.enforceSeenLines ?? true,
        blockAutoGenerated: true,
        planActive: false,
        ...(options.localSandboxRoot !== undefined ? {localSandboxRoot: options.localSandboxRoot} : {}),
        ...(options.vaultRoots !== undefined ? {vaultRoots: [...options.vaultRoots]} : {}),
        homeDir,
        rawInput: false,
    };

    const writeThrough = async (request: EditWriteRequest): Promise<EditWriteResponse> => {
        const approved = await (options.confirmWrite?.(request) ?? true);
        if (!approved) {
            throw new WriteDeniedError(request);
        }
        const target = resolveTarget(options.cwd, request);
        if (request.content === undefined) {
            await unlink(target).catch((error: NodeJS.ErrnoException) => {
                if (error.code !== "ENOENT") throw error;
            });
            return {written: ""};
        }
        await mkdir(dirname(target), {recursive: true});
        await writeFile(target, request.content, "utf-8");
        if (request.moveTo !== undefined) {
            await unlink(request.path).catch((error: NodeJS.ErrnoException) => {
                if (error.code !== "ENOENT") throw error;
            });
        }
        return {written: request.content};
    };

    return {
        name: "edit",
        label: "Edit",
        description: editDescription(mode),
        loadMode: "essential",
        concurrency: "exclusive",
        strict: true,
        approval: "write",
        ...(grammar === null ? {} : {customFormat: {syntax: "lark" as const, definition: grammar}}),
        parameters: {
            type: "object",
            properties: {
                input: {type: "string", description: `${mode} 模式的原文载荷（hashline 为 [path#tag] + 行锚操作）`},
            },
            required: ["input"],
            additionalProperties: false,
        },
        async execute(_toolCallId, params): Promise<AgentToolResult> {
            const args = params as {readonly input?: unknown};
            if (typeof args.input !== "string" || args.input.trim() === "") {
                return errorResult("edit 需要非空 input");
            }

            const session = new EditSession(store, policy, undefined);
            try {
                session.setArgsJson(JSON.stringify({input: args.input}));
                session.finish();
                const outcome = await session.apply({lspFlush: false}, async (error, request) => {
                    if (error !== null) throw error;
                    return writeThrough(request);
                });
                return {
                    content: [{type: "text", text: outcome.text}],
                    details: {
                        mode,
                        files: outcome.files.map((file) => ({path: file.displayPath, op: file.op, warnings: [...file.warnings]})),
                    },
                    isError: outcome.isError,
                };
            } catch (error) {
                if (error instanceof WriteDeniedError) {
                    return errorResult(error.message);
                }
                throw error;
            } finally {
                session.close();
            }
        },
    } as AgentTool;
}

function resolveTarget(cwd: string, request: EditWriteRequest): string {
    if (request.moveTo === undefined) return request.path;
    return isAbsolute(request.moveTo) ? request.moveTo : resolve(cwd, request.moveTo);
}
