import {readProjectRagOverview} from "nbook/server/rag/project-rag-visualization";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {ProjectRagOverviewDtoSchema} from "nbook/shared/dto/project-rag.dto";
import {requireProjectPathQuery} from "nbook/server/utils/novel-chapter";
import {withProjectNotOpenHttpError} from "nbook/server/workspace-files/project-open-guard";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Project RAG"
    ],
    "summary": "Read Project-level subject RAG overview",
    "parameters": [
        {
            "name": "projectPath",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace path, for example workspace/<project>"
            },
            "description": "Project Workspace path, for example workspace/<project>"
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "projectPath": {
                                "type": "string",
                                "minLength": 1
                            },
                            "subjects": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "subjectPath": {
                                            "type": "string",
                                            "minLength": 1,
                                            "pattern": "^simulation\\/subjects\\/[^/]+$"
                                        },
                                        "subjectId": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "metadata": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "name": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "kind": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "profile": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "controlledBy": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "canonicalSource": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "frontmatterError": {
                                                    "nullable": true,
                                                    "type": "string"
                                                }
                                            },
                                            "required": [
                                                "id",
                                                "name",
                                                "kind",
                                                "profile",
                                                "controlledBy",
                                                "canonicalSource",
                                                "frontmatterError"
                                            ],
                                            "additionalProperties": false
                                        },
                                        "eventCount": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 9007199254740991
                                        },
                                        "memoryCount": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 9007199254740991
                                        },
                                        "subjectFileExists": {
                                            "type": "boolean"
                                        },
                                        "soulFileExists": {
                                            "type": "boolean"
                                        },
                                        "mindFileExists": {
                                            "type": "boolean"
                                        },
                                        "stateFileExists": {
                                            "type": "boolean"
                                        },
                                        "sourceStatuses": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "source": {
                                                        "type": "string",
                                                        "enum": [
                                                            "events",
                                                            "memory"
                                                        ]
                                                    },
                                                    "status": {
                                                        "type": "string",
                                                        "enum": [
                                                            "synced",
                                                            "dirty",
                                                            "error",
                                                            "not_indexed",
                                                            "unknown"
                                                        ]
                                                    },
                                                    "recordCount": {
                                                        "type": "integer",
                                                        "minimum": 0,
                                                        "maximum": 9007199254740991
                                                    },
                                                    "indexedAt": {
                                                        "nullable": true,
                                                        "type": "string"
                                                    },
                                                    "lastError": {
                                                        "nullable": true,
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "source",
                                                    "status",
                                                    "recordCount",
                                                    "indexedAt",
                                                    "lastError"
                                                ],
                                                "additionalProperties": false
                                            }
                                        },
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "source": {
                                                        "type": "string",
                                                        "enum": [
                                                            "events",
                                                            "memory"
                                                        ]
                                                    },
                                                    "message": {
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "source",
                                                    "message"
                                                ],
                                                "additionalProperties": false
                                            }
                                        }
                                    },
                                    "required": [
                                        "subjectPath",
                                        "subjectId",
                                        "metadata",
                                        "eventCount",
                                        "memoryCount",
                                        "subjectFileExists",
                                        "soulFileExists",
                                        "mindFileExists",
                                        "stateFileExists",
                                        "sourceStatuses",
                                        "errors"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        },
                        "required": [
                            "projectPath",
                            "subjects"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});





/**
 * 读取当前 Project 的 RAG 可视化概览。
 */
export default defineEventHandler((event) => withProjectNotOpenHttpError(async () => {
    const result = await readProjectRagOverview(runtimePathsFromEnv().workspaceRoot, requireProjectPathQuery(event));
    return ProjectRagOverviewDtoSchema.parse(result);
}));
