import {ProjectRagRebuildRequestDtoSchema, ProjectRagRebuildResultDtoSchema} from "nbook/shared/dto/project-rag.dto";
import {rebuildProjectSubjectRag} from "nbook/server/rag/project-rag-visualization";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {requireProjectPathQuery, validateBody} from "nbook/server/utils/novel-chapter";
import {withProjectNotOpenHttpError} from "nbook/server/workspace-files/project-open-guard";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Project RAG"
    ],
    "summary": "Rebuild subject RAG index for one subject or the current Project",
    "parameters": [
        {
            "name": "projectPath",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace path, for example workspace/<project>"
            },
            "description": "Project Workspace path, for example workspace/<project>"
        }
    ],
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "subjectPath": {
                            "type": "string",
                            "minLength": 1,
                            "pattern": "^simulation\\/subjects\\/[^/]+$"
                        }
                    },
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "projectPath": {
                                "type": "string",
                                "minLength": 1
                            },
                            "rebuiltSubjects": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9007199254740991
                            },
                            "skippedSubjects": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9007199254740991
                            },
                            "results": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "subjectPath": {
                                            "type": "string",
                                            "minLength": 1,
                                            "pattern": "^simulation\\/subjects\\/[^/]+$"
                                        },
                                        "ok": {
                                            "type": "boolean"
                                        },
                                        "message": {
                                            "nullable": true,
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "subjectPath",
                                        "ok",
                                        "message"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        },
                        "required": [
                            "projectPath",
                            "rebuiltSubjects",
                            "skippedSubjects",
                            "results"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});





/**
 * 重建当前 subject 或当前 Project 的 RAG 索引。
 */
export default defineEventHandler((event) => withProjectNotOpenHttpError(async () => {
    const body = await validateBody(event, ProjectRagRebuildRequestDtoSchema);
    const result = await rebuildProjectSubjectRag(runtimePathsFromEnv().workspaceRoot, requireProjectPathQuery(event), body);
    return ProjectRagRebuildResultDtoSchema.parse(result);
}));
