import {ProjectRagSearchRequestDtoSchema, ProjectRagSearchResultDtoSchema} from "nbook/shared/dto/project-rag.dto";
import {searchProjectSubjectRag} from "nbook/server/rag/project-rag-visualization";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {requireProjectPathQuery, validateBody} from "nbook/server/utils/novel-chapter";
import {withProjectNotOpenHttpError} from "nbook/server/workspace-files/project-open-guard";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Project RAG"
    ],
    "summary": "Search one subject through the real RAG chain",
    "parameters": [
        {
            "name": "projectPath",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace path, for example workspace/<project>"
            },
            "description": "Project Workspace path, for example workspace/<project>"
        }
    ],
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "subjectPath": {
                            "type": "string",
                            "minLength": 1,
                            "pattern": "^simulation\\/subjects\\/[^/]+$"
                        },
                        "query": {
                            "type": "string",
                            "minLength": 1
                        },
                        "sources": {
                            "minItems": 1,
                            "type": "array",
                            "items": {
                                "type": "string",
                                "enum": [
                                    "events",
                                    "memory"
                                ]
                            }
                        },
                        "limit": {
                            "type": "integer",
                            "minimum": 1,
                            "maximum": 20
                        }
                    },
                    "required": [
                        "subjectPath",
                        "query"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "projectPath": {
                                "type": "string",
                                "minLength": 1
                            },
                            "subjectPath": {
                                "type": "string",
                                "minLength": 1,
                                "pattern": "^simulation\\/subjects\\/[^/]+$"
                            },
                            "candidates": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "source": {
                                            "type": "string",
                                            "enum": [
                                                "events",
                                                "memory"
                                            ]
                                        },
                                        "text": {
                                            "type": "string"
                                        },
                                        "topic": {
                                            "type": "string"
                                        },
                                        "tick": {
                                            "type": "string"
                                        },
                                        "time": {
                                            "type": "string"
                                        },
                                        "rank": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "sourcePath": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "source",
                                        "text",
                                        "rank",
                                        "sourcePath"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        },
                        "required": [
                            "projectPath",
                            "subjectPath",
                            "candidates"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});





/**
 * 使用真实 subject RAG 链路搜索当前 subject。
 */
export default defineEventHandler((event) => withProjectNotOpenHttpError(async () => {
    const body = await validateBody(event, ProjectRagSearchRequestDtoSchema);
    const result = await searchProjectSubjectRag(runtimePathsFromEnv().workspaceRoot, requireProjectPathQuery(event), body);
    return ProjectRagSearchResultDtoSchema.parse(result);
}));
