import {readProjectRagSubject} from "nbook/server/rag/project-rag-visualization";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {ProjectRagSubjectDtoSchema} from "nbook/shared/dto/project-rag.dto";
import {requireProjectPathQuery} from "nbook/server/utils/novel-chapter";
import {withProjectNotOpenHttpError} from "nbook/server/workspace-files/project-open-guard";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Project RAG"
    ],
    "summary": "Read one subject's RAG data",
    "parameters": [
        {
            "name": "projectPath",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace path, for example workspace/<project>"
            },
            "description": "Project Workspace path, for example workspace/<project>"
        },
        {
            "name": "subjectPath",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project-relative subject path, for example simulation/subjects/<subject-id>"
            },
            "description": "Project-relative subject path, for example simulation/subjects/<subject-id>"
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "projectPath": {
                                "type": "string",
                                "minLength": 1
                            },
                            "subjectPath": {
                                "type": "string",
                                "minLength": 1,
                                "pattern": "^simulation\\/subjects\\/[^/]+$"
                            },
                            "subjectId": {
                                "type": "string",
                                "minLength": 1
                            },
                            "events": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "line": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "tick": {
                                            "type": "string"
                                        },
                                        "time": {
                                            "type": "string"
                                        },
                                        "text": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "line",
                                        "text"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "memories": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "line": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "topic": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "aliases": {
                                            "type": "array",
                                            "items": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "view": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "line",
                                        "topic",
                                        "view"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "sourceStatuses": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "source": {
                                            "type": "string",
                                            "enum": [
                                                "events",
                                                "memory"
                                            ]
                                        },
                                        "status": {
                                            "type": "string",
                                            "enum": [
                                                "synced",
                                                "dirty",
                                                "error",
                                                "not_indexed",
                                                "unknown"
                                            ]
                                        },
                                        "recordCount": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 9007199254740991
                                        },
                                        "indexedAt": {
                                            "nullable": true,
                                            "type": "string"
                                        },
                                        "lastError": {
                                            "nullable": true,
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "source",
                                        "status",
                                        "recordCount",
                                        "indexedAt",
                                        "lastError"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "errors": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "source": {
                                            "type": "string",
                                            "enum": [
                                                "events",
                                                "memory"
                                            ]
                                        },
                                        "message": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "source",
                                        "message"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        },
                        "required": [
                            "projectPath",
                            "subjectPath",
                            "subjectId",
                            "events",
                            "memories",
                            "sourceStatuses",
                            "errors"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});





/**
 * 读取单个 subject 的 RAG 数据。
 */
export default defineEventHandler((event) => withProjectNotOpenHttpError(async () => {
    const query = getQuery(event);
    const subjectPath = typeof query.subjectPath === "string" ? query.subjectPath.trim() : "";
    if (!subjectPath) {
        throw createError({statusCode: 400, message: "subjectPath query 不能为空"});
    }
    const result = await readProjectRagSubject(runtimePathsFromEnv().workspaceRoot, requireProjectPathQuery(event), subjectPath);
    return ProjectRagSubjectDtoSchema.parse(result);
}));
