import {assertNovel, requireProjectPath} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Novels"
    ],
    "summary": "Get a novel",
    "parameters": [
        {
            "name": "novelId",
            "in": "path",
            "required": true,
            "schema": {
                "type": "string"
            }
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "title": {
                                "type": "string"
                            },
                            "summary": {
                                "type": "string"
                            },
                            "workspaceSlug": {
                                "type": "string"
                            },
                            "projectPath": {
                                "type": "string"
                            },
                            "manifestError": {
                                "type": "string"
                            },
                            "createdAt": {
                                "type": "string"
                            },
                            "updatedAt": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "id",
                            "title",
                            "summary",
                            "workspaceSlug",
                            "projectPath",
                            "createdAt",
                            "updatedAt"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});



/**
 * 查询单个 Project Workspace。
 */
export default defineEventHandler(async (event) => {
    return assertNovel(requireProjectPath(event));
});
