import {createError} from "h3";
import {requireProjectPath} from "nbook/server/utils/novel-chapter";
import {projectOccupancy} from "nbook/server/workspace-files/project-session";
import {deleteProjectWorkspace} from "nbook/server/workspace-files/project-workspace-delete";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Novels"
    ],
    "summary": "Delete a novel and its plot data",
    "parameters": [
        {
            "name": "novelId",
            "in": "path",
            "required": true,
            "schema": {
                "type": "string"
            }
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "success": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "success"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});






/**
 * 删除 Project Workspace 目录。
 */
export default defineEventHandler(async (event) => {
    const projectPath = requireProjectPath(event);
    // 占用检查（Task 94 D12，审查后收敛）：仅当有 agent 运行中时拒绝删除——agent 是自主方，
    // 不应把它正在写的项目从脚下删掉。用户自己的 presence 窗口不阻止删除（本地单用户，发起删除者
    // 即在场者，删当前打开的书是正常操作；删除会 close 会话，前端 presence SSE 自然断开）。
    // 与 server/api/projects/item.delete.ts 内联同款逻辑（两处内联，互为镜像）。
    const occupancy = projectOccupancy(projectPath);
    if (occupancy && occupancy.agentActive) {
        throw createError({
            statusCode: 409,
            message: "项目有 agent 正在运行，请先停止 agent 后再删除",
            data: {code: "PROJECT_IN_USE", ...occupancy},
        });
    }
    await deleteProjectWorkspace(runtimePathsFromEnv().workspaceRoot, projectPath);

    return {
        success: true,
    };
});
