import {
    UpdateNovelRequestDtoSchema,
    type UpdateNovelRequestDto,
} from "nbook/shared/dto/novel-chapter.dto";
import {invalidateNovelListCache, requireProjectPath, updateNovelByTool, validateBody} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Novels"
    ],
    "summary": "Update novel title and/or summary",
    "parameters": [
        {
            "name": "novelId",
            "in": "path",
            "required": true,
            "schema": {
                "type": "string"
            }
        }
    ],
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "title": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 120
                        },
                        "summary": {
                            "type": "string",
                            "maxLength": 2000
                        }
                    },
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "title": {
                                "type": "string"
                            },
                            "summary": {
                                "type": "string"
                            },
                            "workspaceSlug": {
                                "type": "string"
                            },
                            "projectPath": {
                                "type": "string"
                            },
                            "manifestError": {
                                "type": "string"
                            },
                            "createdAt": {
                                "type": "string"
                            },
                            "updatedAt": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "id",
                            "title",
                            "summary",
                            "workspaceSlug",
                            "projectPath",
                            "createdAt",
                            "updatedAt"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});



/**
 * 更新 Project manifest 信息。
 */
export default defineEventHandler(async (event) => {
    const projectPath = requireProjectPath(event);
    const body = await validateBody<UpdateNovelRequestDto>(event, UpdateNovelRequestDtoSchema);
    const result = await updateNovelByTool(projectPath, body);
    invalidateNovelListCache();
    return result;
});
