import {listNovels} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Novels"
    ],
    "summary": "List all novels",
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "title": {
                                    "type": "string"
                                },
                                "summary": {
                                    "type": "string"
                                },
                                "workspaceSlug": {
                                    "type": "string"
                                },
                                "projectPath": {
                                    "type": "string"
                                },
                                "manifestError": {
                                    "type": "string"
                                },
                                "createdAt": {
                                    "type": "string"
                                },
                                "updatedAt": {
                                    "type": "string"
                                },
                                "volumeCount": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 9007199254740991
                                },
                                "chapterCount": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 9007199254740991
                                },
                                "totalWords": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 9007199254740991
                                },
                                "lorebookCount": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 9007199254740991
                                },
                                "sessionCount": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 9007199254740991
                                },
                                "threadCount": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 9007199254740991
                                },
                                "sceneCount": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 9007199254740991
                                },
                                "plotCount": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 9007199254740991
                                }
                            },
                            "required": [
                                "id",
                                "title",
                                "summary",
                                "workspaceSlug",
                                "projectPath",
                                "createdAt",
                                "updatedAt",
                                "volumeCount",
                                "chapterCount",
                                "totalWords",
                                "lorebookCount",
                                "sessionCount",
                                "threadCount",
                                "sceneCount",
                                "plotCount"
                            ],
                            "additionalProperties": false
                        }
                    }
                }
            }
        }
    }
} as never,
});



/**
 * 查询 Project Workspace 列表。
 */
export default defineEventHandler(async () => listNovels());
